apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hjworks-lb
  name: hjworks-lb
spec:
  ports:
  - name: 8081-80
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: hjworks-lb
  type: LoadBalancer
status:
  loadBalancer: {}
